version: "3.9"

services:
  database:
    image: postgres
    container_name: teste_backend_pedidu
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedidu_backend_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
