version: "3.9"

services:
  backend:
    build: .
    container_name: backend_pedidu
    ports:
      - 3333:3333
    restart: always
    volumes:
      - .:/usr/server
    environment:
      - SECRET_KEY=secret
      - PGHOST=database
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASS=postgres
      - PG_DATABASE=pedidu_backend_db
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    container_name: teste_backend_pedidu
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedidu_backend_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
